

const cards = [
    {
      id: 1,
      img: "/1.jpg",
      category: "Fruits",
      name: "strawberry",
      amount: 10000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 2,
      img: "/2.jpg",
      category: "Vegetables",
      name: "onion",
      amount: 13000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 3,
      img: "/3.jpg",
      category: "Vegetables",
      name: "tomato",
      amount: 15000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 4,
      img: "/4.jpg",
      category: "Vegetables",
      name: "eggplant",
      amount: 12500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 5,
      img: "/5.jpg",
      category: "Vegetables",
      name: "Broccoli",
      amount: 8500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    //{ id: 6, img: "/6.jpg", category:'', name: "Potato", amount: 10000, total:0, cart:false, quantity:0, likes:false },
    {
      id: 7,
      img: "/7.jpg",
      category: "Vegetables",
      name: "Carrot",
      amount: 12000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 8,
      img: "/8.jpg",
      category: "Vegetables",
      name: "Cauliflower",
      amount: 8000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 9,
      img: "/9.jpg",
      category: "Fruits",
      name: "Cucumber",
      amount: 4000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 10,
      img: "/10.jpg",
      category: "Vegetables",
      name: "Garlic",
      amount: 16500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 11,
      img: "/11.jpg",
      category: "Vegetables",
      name: "Sweet pepper",
      amount: 7000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 12,
      img: "/12.jpg",
      category: "Vegetables",
      name: "Lettuce",
      amount: 18000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 13,
      img: "/13.jpg",
      category: "Vegetables",
      name: "Red pepper",
      amount: 2000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 14,
      img: "/14.jpg",
      category: "Fruits",
      name: "Watermelon",
      amount: 22500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 15,
      img: "/15.jpg",
      category: "Vegetables",
      name: "Mushroom",
      amount: 11500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 16,
      img: "/16.jpg",
      category: "Fruits",
      name: "Banana",
      amount: 14500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 17,
      img: "/17.jpg",
      category: "Vegetables",
      name: "Pumpkin",
      amount: 15000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 18,
      img: "/18.jpg",
      category: "Fruits",
      name: "Pineapple",
      amount: 19000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 19,
      img: "/19.jpg",
      category: "Nuts",
      name: "Almonds",
      amount: 12000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 20,
      img: "/20.jpg",
      category: "Fruits",
      name: "Apple",
      amount: 13200,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 21,
      img: "/21.jpg",
      category: "Nuts",
      name: "Hazelnut",
      amount: 17400,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 22,
      img: "/22.jpg",
      category: "Nuts",
      name: "Pistachio",
      amount: 14400,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 23,
      img: "/23.jpg",
      category: "Fruits",
      name: "Orange",
      amount: 25000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 24,
      img: "/24.jpg",
      category: "Nuts",
      name: "Sunflower seed",
      amount: 23200,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 25,
      img: "/25.jpg",
      category: "Nuts",
      name: "Walnut",
      amount: 7400,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 26,
      img: "/26.jpg",
      category: "Fruits",
      name: "Cherry",
      amount: 4800,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 27,
      img: "/27.jpg",
      category: "Fruits",
      name: "Fig",
      amount: 5600,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 28,
      img: "/28.jpg",
      category: "Beans",
      name: "Green Peas",
      amount: 3600,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 29,
      img: "/29.jpg",
      category: "Fruits",
      name: "Kiwi",
      amount: 11500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 30,
      img: "/30.jpg",
      category: "Beans",
      name: "Green Peas",
      amount: 21000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 31,
      img: "/31.jpg",
      category: "Beans",
      name: "Red beans",
      amount: 22000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 32,
      img: "/32.jpg",
      category: "Fruits",
      name: "Grape",
      amount: 18300,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 33,
      img: "/33.jpg",
      category: "Fruits",
      name: "Lemon",
      amount: 15800,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 34,
      img: "/34.jpg",
      category: "Fruits",
      name: "Cantaloupe",
      amount: 7000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 35,
      img: "/35.jpg",
      category: "Beans",
      name: "Lentils",
      amount: 13000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 36,
      img: "/36.jpg",
      category: "Vegetables",
      name: "Radish",
      amount: 14500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 37,
      img: "/37.jpg",
      category: "Vegetables",
      name: "Corn",
      amount: 22000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
  ];

  export default cards;