import img1 from '@/public/1.jpg'
import img2 from '@/public/2.jpg'
import img3 from '@/public/3.jpg'
import img4 from '@/public/4.jpg'
import img5 from '@/public/5.jpg'
import img6 from '@/public/6.jpg'
import img7 from '@/public/7.jpg'
import img8 from '@/public/8.jpg'
import img9 from '@/public/9.jpg'
import img10 from '@/public/10.jpg'
import img11 from '@/public/11.jpg'
import img12 from '@/public/12.jpg'
import img13 from '@/public/13.jpg'
import img14 from '@/public/14.jpg'
import img15 from '@/public/15.jpg'
import img16 from '@/public/16.jpg'
import img17 from '@/public/17.jpg'
import img18 from '@/public/18.jpg'
import img19 from '@/public/19.jpg'
import img20 from '@/public/20.jpg'
import img21 from '@/public/21.jpg'
import img22 from '@/public/22.jpg'
import img23 from '@/public/23.jpg'
import img24 from '@/public/24.jpg'
import img25 from '@/public/25.jpg'
import img26 from '@/public/26.jpg'
import img27 from '@/public/27.jpg'
import img28 from '@/public/28.jpg'
import img29 from '@/public/29.jpg'
import img30 from '@/public/30.jpg'
import img31 from '@/public/31.jpg'
import img32 from '@/public/32.jpg'
import img33 from '@/public/33.jpg'
import img34 from '@/public/34.jpg'
import img35 from '@/public/35.jpg'
import img36 from '@/public/36.jpg'
import img37 from '@/public/37.jpg'


const cards = [
    {
      id: 1,
      img:img1,
      category: "Fruits",
      name: "strawberry",
      amount: 10000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 2,
      img:img2,
      category: "Vegetables",
      name: "onion",
      amount: 13000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 3,
      img:img3,
      category: "Vegetables",
      name: "tomato",
      amount: 15000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 4,
      img:img4,
      category: "Vegetables",
      name: "eggplant",
      amount: 12500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 5,
      img:img5,
      category: "Vegetables",
      name: "Broccoli",
      amount: 8500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    //{ id: 6, img:img6, category:'', name: "Potato", amount: 10000, total:0, cart:false, quantity:0, likes:false },
    {
      id: 7,
      img:img7,
      category: "Vegetables",
      name: "Carrot",
      amount: 12000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 8,
      img:img8,
      category: "Vegetables",
      name: "Cauliflower",
      amount: 8000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 9,
      img:img9,
      category: "Fruits",
      name: "Cucumber",
      amount: 4000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 10,
      img:img10,
      category: "Vegetables",
      name: "Garlic",
      amount: 16500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 11,
      img:img11,
      category: "Vegetables",
      name: "Sweet pepper",
      amount: 7000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 12,
      img:img12,
      category: "Vegetables",
      name: "Lettuce",
      amount: 18000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 13,
      img:img13,
      category: "Vegetables",
      name: "Red pepper",
      amount: 2000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 14,
      img:img14,
      category: "Fruits",
      name: "Watermelon",
      amount: 22500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 15,
      img:img15,
      category: "Vegetables",
      name: "Mushroom",
      amount: 11500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 16,
      img:img16,
      category: "Fruits",
      name: "Banana",
      amount: 14500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 17,
      img:img17,
      category: "Vegetables",
      name: "Pumpkin",
      amount: 15000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 18,
      img:img18,
      category: "Fruits",
      name: "Pineapple",
      amount: 19000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 19,
      img:img19,
      category: "Nuts",
      name: "Almonds",
      amount: 12000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 20,
      img:img20,
      category: "Fruits",
      name: "Apple",
      amount: 13200,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 21,
      img:img21,
      category: "Nuts",
      name: "Hazelnut",
      amount: 17400,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 22,
      img:img22,
      category: "Nuts",
      name: "Pistachio",
      amount: 14400,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 23,
      img:img23,
      category: "Fruits",
      name: "Orange",
      amount: 25000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 24,
      img:img24,
      category: "Nuts",
      name: "Sunflower seed",
      amount: 23200,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 25,
      img:img25,
      category: "Nuts",
      name: "Walnut",
      amount: 7400,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 26,
      img:img26,
      category: "Fruits",
      name: "Cherry",
      amount: 4800,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 27,
      img:img27,
      category: "Fruits",
      name: "Fig",
      amount: 5600,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 28,
      img:img28,
      category: "Beans",
      name: "Green Peas",
      amount: 3600,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 29,
      img:img29,
      category: "Fruits",
      name: "Kiwi",
      amount: 11500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 30,
      img:img30,
      category: "Beans",
      name: "Green Peas",
      amount: 21000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 31,
      img:img31,
      category: "Beans",
      name: "Red beans",
      amount: 22000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 32,
      img:img32,
      category: "Fruits",
      name: "Grape",
      amount: 18300,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 33,
      img:img33,
      category: "Fruits",
      name: "Lemon",
      amount: 15800,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 34,
      img:img34,
      category: "Fruits",
      name: "Cantaloupe",
      amount: 7000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 35,
      img:img35,
      category: "Beans",
      name: "Lentils",
      amount: 13000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 36,
      img:img36,
      category: "Vegetables",
      name: "Radish",
      amount: 14500,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
    {
      id: 37,
      img:img37,
      category: "Vegetables",
      name: "Corn",
      amount: 22000,
      total:0,
      cart: false,
      quantity: 0,
      likes:false,
    },
  ];

  export default cards;